### ISSUE TITLE
The leaderboard is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [spraakbanken/SuperLim-2#1]
Check this link but found:
<img width="967" alt="1710969553233" src="https://github.com/spraakbanken/SuperLim-2/assets/8592144/2bb4917a-8a5c-4525-90b9-7c9fecf652b7">
<img width="734" alt="1710969505439" src="https://github.com/spraakbanken/SuperLim-2/assets/8592144/2beed979-46fd-4676-ae62-98452f35e9d3">
Here is the link: https://lab.kb.se/leaderboard/results

**Comment by AleksandrsBerdicevskis** [comment]
Thanks for the heads up. I notified our colleagues at KB about the problem.

**Comment by AleksandrsBerdicevskis** [comment]
Now it's back online!
